[package]
name = "qi_cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
qi_core = { path = "../core" }
qi_interactive = { path = "../interactive" }

